name: traveltrace
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.12.1         # Updated to latest compatible version
  lottie: ^3.3.1
  image_picker: ^1.1.2
  font_awesome_flutter: ^10.8.0
  table_calendar: ^3.2.0
  http: ^1.1.0                          # Add this to support API requests

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - images/travel.png
